config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :tasks
  end

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  name       :string
#  status     :integer          default("to_do")
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :user

  enum status: %i(to_do doing done)

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_user
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = @user.tasks.new
  end

  def edit
  end

  def create
    @task = @user.tasks.new(task_params)

    if @task.save
      redirect_to user_path(@user)
    else
      redirect_to new_user_task_path(@user), danger: "Name field is required"
    end
  end

  def update
    if @task.update(task_params)
     redirect_to user_path(@user)
    else
      redirect_to edit_user_task_path(@user, @task), danger: "Name field is required"
    end
  end

  def destroy
    @user.tasks.destroy(@task)
    redirect_to user_path(@user)
  end

  private

    def get_user
      @user = User.find(params[:user_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      redirect_to new_user_path, danger: "Both fields are required"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user), danger: "Both fields are required"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDosApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-danger">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.slim
= simple_form_for([@user, @task]) do |form|
  .row
    - if @task.persisted?
      .col-md-2
        = form.input :name, label: "Name"
      .col-md-2
        label for="status" Status
        br
        = form.select :status, options_for_select(Task.statuses.map{|key, value| [key.titleize, Task.statuses.key(value)]}, @task.status)
      .col-md-1.form-button.delete-color
        = link_to 'Delete Task', user_task_path(@user, @task), data: {confirm: "Are you sure?"}, :method => :delete
    - else
      .col-md-2
        = form.input :name, label: "name"
    .col-md-1.submit-button
      = form.button :submit

app/views/tasks/edit.html.slim
h1 Editing task

== render "form"

app/views/tasks/new.html.slim
h1 New task

== render "form"

app/views/users/_form.html.slim
= simple_form_for @user do |form|
  .row
    .col-md-2 
      = form.input :name, label: "nombre"
    .col-md-2
      = form.input :email
    .col-md-1.submit-button
      = form.button :submit

app/views/users/edit.html.slim
h1 Editing user
= render "form"

app/views/users/index.html.slim
.text-center
  h1 Listing users

table.table.table-striped.table-hover.text-center
  thead
    tr
      th Name
      th Count
  tbody
    - @users.each do |user|
      tr
        td.bold = link_to user.name, user
        td = user.tasks.count

.row
  col-md-12.text-center
    = link_to "New User", new_user_path

app/views/users/new.html.slim
h1 New user

== render "form"

app/views/users/show.html.slim
.text-center
  h1 = @user.name

table.table.table-striped.table-hover.text-center
  thead
    tr
      th Task
      th Status
      th Edit task
  tbody
    - @user.tasks.each do |task|
      tr
        td = task.name
        td = task.status.titleize
        td = link_to "Edit", edit_user_task_path(@user, task)
  tfoot
    tr
      td = link_to "New todo", new_user_task_path(@user)
      td colspan="2" &nbsp

.row.text-center
  .col-md-6
    = link_to "Delete user", @user, data: {confirm: "Are you sure?"}, method: :delete
  .col-md-6
    = link_to "Edit user", edit_user_path(@user)